---
title: "gp sim"
author: "TJ Mahr"
date: "December 29, 2016"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Adapting from here: https://gist.github.com/mrecos/2e04349935534f317a86a260095dafe0

```{r}
library(rstan)

eta_sq = 1
rho_sq = 1
sigma_sq = 0.0001
x <- seq(-10, 10, 0.1)
n <- length(x)
iter = 100
chains = 1
rho_sq_range = c(0.01, 0.1, 1, 10) # for faceted kernel plot
eta_sq_prior = c(0.1, 1, 10)
rho_sq_prior = c(0.1, 1, 10)

# new data for fit
x1 <- c(-6, -3, -1, 0, 2, 4, 7, 9)
y1 <- c(-2, 0, 1, -1, 0, 2.5, 0, 3)

```

```{r}
## Simulate with a few noise-free data points to get posterior.
## still fixed values for eta and rho
## Again pretend the noise is almost zero, but not quite.
stan_data <- list(
  x1 = x1, y1 = y1, N1 = length(x1), x2 = x, N2 = length(x), 
  eta_sq = eta_sq, rho_sq = rho_sq, sigma_sq = sigma_sq
)

fit2 <- stan(
  file = "gp-predict-se.stan", 
  data = stan_data, 
  iter = iter, 
  chains = chains)

sims2 <- extract(fit2, permuted = TRUE)

## Rearrange the data for plotting
se_sim_data2 <- plyr::adply(sims2$y, 2)
tmp2 <- reshape2::melt(se_sim_data2)
names(tmp2) <- c("xid", "group", "y")
tmp2 <- plyr::mutate(tmp2, x = x[xid])
# plot it
fig2b <- ggplot(data = tmp2, aes(x=x, y=y)) +
  geom_line(aes(group=group, color = group), alpha=0.2) +
  theme_bw() +
  geom_point(data=data.frame(x=x1, y=y1), aes(x=x1, y = y1), size = 3) +
  geom_point(data=data.frame(x=x1, y=y1), aes(x=x1, y = y1),
             size = 6, color = "black", shape = 1) +
  labs(caption=paste0("rho_sq = ", rho_sq, ", eta_sq = ", eta_sq, ", sigma_sq = ", sigma_sq),
       x = "X", 
       y = "Y") +
  # scale_x_continuous(limits = c(-10,10), breaks = seq(-10,10,by=1), labels = seq(-10,10,by=1)) +
  # scale_y_continuous(limits = c(-3,3), breaks = seq(-3,3,by=1), labels = seq(-3,3,by=1)) +
  theme(
    panel.border = element_rect(colour = "gray90"),
    axis.text.x = element_text(angle = 0, size = 6, family = "Trebuchet MS"),
    axis.text.y = element_text(size = 6, family = "Trebuchet MS"),
    axis.title = element_text(size = 8, family = "Trebuchet MS"),
    plot.caption = element_text(size = 8, hjust=0, 
                                family = "Trebuchet MS"),
    plot.title=element_text(family="TrebuchetMS-Bold"),
    plot.subtitle=element_text(family="TrebuchetMS-Italic"),
    legend.position="none"
  )
plot(fig2b)
```

